# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

WORKDIR /app

# Install system dependencies for web3
RUN apk add --no-cache gcc musl-dev libffi-dev

# Copy entire repository into container
COPY . .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Expose the MCP server port
EXPOSE 3000

# Start the MCP server
CMD ["python", "server.py"]
